site:
  id: np-template-docs
  base_url: "http://127.0.0.1:9000/" # must end with /
  media_base_url: "http://127.0.0.1:9000/media/" # must end with /
  title: "Notepub Docs Template"
  description: "Template repository for documentation websites powered by Notepub."
  default_og_image: "/assets/notepub.jpg"
  analytics:
    enabled: false
    provider: "yandex_metrika"
    yandex_counter_id: ""
content:
  source: "local"
  local_dir: "../content"
paths:
  file_root: ./.notepub
  artifacts_dir: ./.notepub/artifacts
  snapshot_file: ./.notepub/snapshot/objects.json
  cache_root: ./.notepub/cache
theme:
  dir: "./.np"
  name: "theme"
  templates_subdir: "templates"
  assets_subdir: "assets"
rules_path: "./.np/rules.yaml"
server:
  listen: "127.0.0.1:8080"
cache:
  html_ttl_seconds: 600
  stale_if_error_seconds: 604800
